import type { Metadata } from "next";
import CopyRight from "@/ui/footer/copy-right";
import Footer from "@/ui/footer/footer";
import Header from "@/ui/header/header";
import Nav from "@/ui/nav/nav";

export const metadata: Metadata = {
	title: "Shop",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<>
			<Header />
			<Nav />
			{children}
			<Footer />
			<CopyRight />
		</>
	);
}
